version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      - POSTGRES_DB=smtr
      - POSTGRES_USER=u_smtr_rw
      - POSTGRES_PASSWORD=usmtrrw
    volumes:
      - ./smart-tracer-api/migrations/init:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - back-end
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    build: "."
    container_name: node_container
    depends_on: postgres
    ports: 4000:4000
